import type { PartVariant, Position } from "./portal-types";

// Данные взяты из таблицы maxmobiles:
//  - БД_УСЛУГИ_РО (работы по iPhone 16): строки 908..925, коды i16-*
//  - БД_ЗАПЧАСТИ (варианты дисплея iPhone 16): строки 275..279
// Поля sheetRef показывают пользователю, где в исходной Google-таблице раньше жила эта величина.

const round = (n: number, p: number = 1000) => Math.round(n * p) / p;

const DISPLAY_VARIANTS_IP16: PartVariant[] = [
  {
    id: "service_orig",
    shortName: "Сервисный orig",
    fullName: "iPhone 16 [DIS] Дисплей - Сервисный оригинал (подлинное)",
    sources: [
      { key: "icomponents", label: "iComponents", price: null, sheetRef: "БД_ЗАПЧАСТИ!I275" },
      { key: "moslcd", label: "MOS-LCD", price: null, sheetRef: "БД_ЗАПЧАСТИ!L275" },
    ],
    markupPct: 0.12,
    roundStep: 50,
    partPurchaseSheetRef: "БД_ЗАПЧАСТИ!M275",
    partRetailSheetRef: "БД_ЗАПЧАСТИ!P275",
    draft: true,
  },
  {
    id: "removed_orig_used",
    shortName: "Снятый orig (бу)",
    fullName: "iPhone 16 [DIS] Дисплей - Снятый оригинал (бу)",
    sources: [
      { key: "icomponents", label: "iComponents", price: 13900, sheetRef: "БД_ЗАПЧАСТИ!I276" },
      { key: "moslcd", label: "MOS-LCD", price: null, sheetRef: "БД_ЗАПЧАСТИ!L276" },
    ],
    markupPct: round(0.173),
    roundStep: 50,
    partPurchaseSheetRef: "БД_ЗАПЧАСТИ!M276",
    partRetailSheetRef: "БД_ЗАПЧАСТИ!P276",
  },
  {
    id: "removed_orig_unknown",
    shortName: "Снятый orig (неизв)",
    fullName: "iPhone 16 [DIS] Дисплей - Снятый оригинал (неизвестная деталь)",
    sources: [
      { key: "icomponents", label: "iComponents", price: 13200, sheetRef: "БД_ЗАПЧАСТИ!I277" },
      { key: "moslcd", label: "MOS-LCD", price: null, sheetRef: "БД_ЗАПЧАСТИ!L277" },
    ],
    markupPct: 0.18,
    roundStep: 50,
    partPurchaseSheetRef: "БД_ЗАПЧАСТИ!M277",
    partRetailSheetRef: "БД_ЗАПЧАСТИ!P277",
  },
  {
    id: "refurb_orig_used",
    shortName: "Восст orig (бу)",
    fullName: "iPhone 16 [DIS] Дисплей - Восстановленный оригинал (бу)",
    sources: [
      { key: "icomponents", label: "iComponents", price: 13400, sheetRef: "БД_ЗАПЧАСТИ!I278" },
      { key: "moslcd", label: "MOS-LCD", price: 13990, sheetRef: "БД_ЗАПЧАСТИ!L278" },
    ],
    markupPct: 0.13,
    roundStep: 50,
    partPurchaseSheetRef: "БД_ЗАПЧАСТИ!M278",
    partRetailSheetRef: "БД_ЗАПЧАСТИ!P278",
  },
  {
    id: "refurb_orig_unknown",
    shortName: "Восст orig (неизв)",
    fullName: "iPhone 16 [DIS] Дисплей - Восстановленный оригинал (неизвестная деталь)",
    sources: [
      { key: "icomponents", label: "iComponents", price: null, sheetRef: "БД_ЗАПЧАСТИ!I279" },
      { key: "moslcd", label: "MOS-LCD", price: 13690, sheetRef: "БД_ЗАПЧАСТИ!L279" },
    ],
    markupPct: 0.12,
    roundStep: 50,
    partPurchaseSheetRef: "БД_ЗАПЧАСТИ!M279",
    partRetailSheetRef: "БД_ЗАПЧАСТИ!P279",
  },
];

export const REAL_CATALOG: Position[] = [
  // ── iPhone 16 ────────────────────────────────────────────────────────────
  {
    id: "iphone16.display",
    device: "iPhone 16",
    category: "Дисплей",
    variant: "замена (5 вариантов запчасти)",
    code: "i16-DIS",
    warranty: "90 дней",
    laborMinutes: 40,
    laborPrice: 7000,
    laborSheetRef: "БД_УСЛУГИ_РО!P916",
    groupPath: "Ремонт iPhone > iPhone 16",
    variants: DISPLAY_VARIANTS_IP16,
  },
  {
    id: "iphone16.display_e",
    device: "iPhone 16",
    category: "Дисплей",
    variant: "устранение уведомления о замене",
    code: "i16-DISE",
    warranty: "90 дней",
    laborMinutes: 30,
    laborPrice: 6300,
    laborSheetRef: "БД_УСЛУГИ_РО!P917",
    groupPath: "Ремонт iPhone > iPhone 16",
  },
  {
    id: "iphone16.display_glass",
    device: "iPhone 16",
    category: "Дисплей",
    variant: "переклей разбитого стекла",
    code: "i16-DGL",
    warranty: "90 дней",
    laborMinutes: 90,
    laborPrice: 20000,
    laborSheetRef: "БД_УСЛУГИ_РО!P918",
    groupPath: "Ремонт iPhone > iPhone 16",
  },
  {
    id: "iphone16.battery",
    device: "iPhone 16",
    category: "Аккумулятор",
    variant: "замена",
    code: "i16-BAT",
    warranty: "90 дней",
    laborMinutes: 25,
    laborPrice: 7800,
    laborSheetRef: "БД_УСЛУГИ_РО!P913",
    groupPath: "Ремонт iPhone > iPhone 16",
  },
  {
    id: "iphone16.battery_e",
    device: "iPhone 16",
    category: "Аккумулятор",
    variant: "устранение уведомления о замене",
    code: "i16-BATE",
    warranty: "90 дней",
    laborMinutes: 20,
    laborPrice: 0,
    laborSheetRef: "БД_УСЛУГИ_РО!P914",
    groupPath: "Ремонт iPhone > iPhone 16",
    draft: true,
  },
  {
    id: "iphone16.charging_port",
    device: "iPhone 16",
    category: "Разъём зарядки",
    variant: "замена",
    code: "i16-CHG",
    warranty: "90 дней",
    laborMinutes: 60,
    laborPrice: 7500,
    laborSheetRef: "БД_УСЛУГИ_РО!P915",
    groupPath: "Ремонт iPhone > iPhone 16",
  },
  {
    id: "iphone16.camera_main",
    device: "iPhone 16",
    category: "Камера основная",
    variant: "замена",
    code: "i16-CAMR",
    warranty: "90 дней",
    laborMinutes: 30,
    laborPrice: 7000,
    laborSheetRef: "БД_УСЛУГИ_РО!P919",
    groupPath: "Ремонт iPhone > iPhone 16",
  },
  {
    id: "iphone16.camera_front",
    device: "iPhone 16",
    category: "Камера фронтальная",
    variant: "замена",
    code: "i16-CAMF",
    warranty: "90 дней",
    laborMinutes: 35,
    laborPrice: 7600,
    laborSheetRef: "БД_УСЛУГИ_РО!P920",
    groupPath: "Ремонт iPhone > iPhone 16",
  },
  {
    id: "iphone16.camera_glass",
    device: "iPhone 16",
    category: "Камера",
    variant: "замена разбитого стекла (1 шт)",
    code: "i16-CGL",
    warranty: "90 дней",
    laborMinutes: 30,
    laborPrice: 4300,
    laborSheetRef: "БД_УСЛУГИ_РО!P921",
    groupPath: "Ремонт iPhone > iPhone 16",
  },
  {
    id: "iphone16.face_id",
    device: "iPhone 16",
    category: "Face ID",
    variant: "восстановление",
    code: "i16-FID",
    warranty: "90 дней",
    laborMinutes: 60,
    laborPrice: 9700,
    laborSheetRef: "БД_УСЛУГИ_РО!P922",
    groupPath: "Ремонт iPhone > iPhone 16",
  },
  {
    id: "iphone16.back_glass",
    device: "iPhone 16",
    category: "Заднее стекло",
    variant: "замена",
    code: "i16-BGL",
    warranty: "90 дней",
    laborMinutes: 60,
    laborPrice: 4900,
    laborSheetRef: "БД_УСЛУГИ_РО!P923",
    groupPath: "Ремонт iPhone > iPhone 16",
  },
  {
    id: "iphone16.housing",
    device: "iPhone 16",
    category: "Корпус",
    variant: "замена",
    code: "i16-HSG",
    warranty: "90 дней",
    laborMinutes: 120,
    laborPrice: 11450,
    laborSheetRef: "БД_УСЛУГИ_РО!P924",
    groupPath: "Ремонт iPhone > iPhone 16",
  },
  {
    id: "iphone16.diagnostics",
    device: "iPhone 16",
    category: "Диагностика",
    variant: "с пайкой компонентов",
    code: "i16-DGN",
    warranty: "—",
    laborMinutes: 30,
    laborPrice: 1,
    laborSheetRef: "БД_УСЛУГИ_РО!P908",
    groupPath: "Ремонт iPhone > iPhone 16",
  },
  {
    id: "iphone16.cleaning",
    device: "iPhone 16",
    category: "Чистка",
    variant: "сетки динамиков и разъёма (с разборкой)",
    code: "i16-CLN",
    warranty: "—",
    laborMinutes: 60,
    laborPrice: 6700,
    laborSheetRef: "БД_УСЛУГИ_РО!P912",
    groupPath: "Ремонт iPhone > iPhone 16",
  },
  {
    id: "iphone16.cleaning_no_disasm",
    device: "iPhone 16",
    category: "Чистка",
    variant: "сетки динамиков и разъёма (без разборки)",
    code: "i16-CLNB",
    warranty: "—",
    laborMinutes: 15,
    laborPrice: 700,
    laborSheetRef: "БД_УСЛУГИ_РО!P911",
    groupPath: "Ремонт iPhone > iPhone 16",
  },
  {
    id: "iphone16.water_protect_1",
    device: "iPhone 16",
    category: "Пылевлагозащита",
    variant: "этап 1 — восстановление",
    code: "i16-WTR1",
    warranty: "—",
    laborMinutes: 30,
    laborPrice: 1450,
    laborSheetRef: "БД_УСЛУГИ_РО!P909",
    groupPath: "Ремонт iPhone > iPhone 16",
  },
  {
    id: "iphone16.water_protect_2",
    device: "iPhone 16",
    category: "Пылевлагозащита",
    variant: "этап 2 — восстановление",
    code: "i16-WTR2",
    warranty: "—",
    laborMinutes: 30,
    laborPrice: 1450,
    laborSheetRef: "БД_УСЛУГИ_РО!P910",
    groupPath: "Ремонт iPhone > iPhone 16",
  },
];
